version: '3'
services:
  web:
    image: server
    container_name: web
    command: bash -c "gunicorn modelproject.wsgi:application -b 0.0.0.0:8000" # 서버 실행
    ports:
      - "8000:8000" # 외부에서 들어오는 포트 번호:내부에서 보낼 포트 번호
    restart: always
    volumes:
      - .:/app
      - ./static:/app/static
#      - ./media:/app/media
    networks:
      - server

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf # nginx 설정 파일을 연결시킴
      - ./static:/static
#      - ./media:/media # media가 있으면
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - web # nginx 컨테이너가 있기 위해서는 web 컨테이너가 미리 존재해야 함
    networks:
      - server

networks:
  server: